name = "acumen-wc"
pages_build_output_dir = "dist"

[vars]
NUXT_PUBLIC_HUBSPOT_PORTAL_ID = "21977584"
NUXT_PUBLIC_HUBSPOT_FORM_ID = "7a16225c-5c3a-42d9-95a0-35cd8b2cbf1a"
FUNRAISE_API_KEY = "MjY1YmY4NWUtNjYwMi00OTA0LWEyNjQtOGVkNzA2Njk5NTA0LkEyejhnLUhtTXYwRkthX19GVUxVRW5wY3pWSGxYUHZYQ3c1cmpUc2Z1MUE"
NUXT_PUBLIC_CLARITY_PROJECT_ID = "wgbkmq11it"